// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/otp/generate": {
            "post": {
                "description": "Generate a secure OTP code and send it to the specified phone number via the interface API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "otp"
                ],
                "summary": "Generate and send OTP",
                "parameters": [
                    {
                        "description": "OTP generation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/otp.GenerateOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP sent successfully",
                        "schema": {
                            "$ref": "#/definitions/otp.GenerateOTPResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "$ref": "#/definitions/otp.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/otp.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/otp/verify": {
            "post": {
                "description": "Verify an OTP code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "otp"
                ],
                "summary": "Verify OTP",
                "parameters": [
                    {
                        "description": "OTP verification request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/otp.VerifyOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP verified successfully",
                        "schema": {
                            "$ref": "#/definitions/otp.VerifyOTPResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "$ref": "#/definitions/otp.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/otp.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "TooManyRequests",
                        "schema": {
                            "$ref": "#/definitions/otp.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/otp.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/platforms": {
            "get": {
                "description": "List all available platforms and their device IDs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "platforms"
                ],
                "summary": "List available platforms",
                "responses": {
                    "200": {
                        "description": "List of platforms retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/platforms.Platform"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/platforms.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "otp.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "message"
                }
            }
        },
        "otp.GenerateOTPRequest": {
            "type": "object",
            "required": [
                "device_id",
                "phone_number",
                "platform"
            ],
            "properties": {
                "device_id": {
                    "type": "string",
                    "example": "+237123456789"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+237123456780"
                },
                "platform": {
                    "type": "string",
                    "example": "wa"
                }
            }
        },
        "otp.GenerateOTPResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string",
                    "example": "2026-02-19T20:30:00Z"
                },
                "message": {
                    "type": "string",
                    "example": "OTP sent successfully"
                }
            }
        },
        "otp.VerifyOTPRequest": {
            "type": "object",
            "required": [
                "code",
                "device_id",
                "phone_number",
                "platform"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "123456"
                },
                "device_id": {
                    "type": "string",
                    "example": "+237123456789"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+237123456780"
                },
                "platform": {
                    "type": "string",
                    "example": "wa"
                }
            }
        },
        "otp.VerifyOTPResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "OTP verified successfully"
                }
            }
        },
        "platforms.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "message"
                }
            }
        },
        "platforms.Platform": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string",
                    "example": "+237123456789"
                },
                "platform": {
                    "type": "string",
                    "example": "wa"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Authy API",
	Description:      "API for Authy service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
