name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: PATH
          script: |
            set -e
            export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
            cd /opt/shortmesh/Authy-API
            git pull
            corepack enable
            cd pkg/web && make install && make build && cd ../..
            make build
            sudo systemctl restart authy-api.service
